"""Remove telegram_message_id and comment from posts

Revision ID: a2beccf5b23c
Revises: f1868fafa851
Create Date: 2026-01-23 14:40:09.512171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2beccf5b23c'
down_revision: Union[str, None] = 'f1868fafa851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'telegram_message_id')
    op.drop_column('posts', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('telegram_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
