"""Add telegram_message_id and comment to posts

Revision ID: f1868fafa851
Revises: 2265f91b3a26
Create Date: 2026-01-23 14:28:17.433439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1868fafa851'
down_revision: Union[str, None] = '2265f91b3a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comment')
    op.drop_column('posts', 'telegram_message_id')
    # ### end Alembic commands ###
